name: deploy to server
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

   
    - name: deploy to the development server
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /cd node-learning/farmer-ecommerce &&
            git pull origin development &&
            npm install &&
            npm start || { echo 'Deployment failed' && exit 1; }
